### PR TITLE
Interlok 3004 UI optional components

### PR DESCRIPTION
**Pull request by higgyfella**
## Motivation

I am doing this so any developer can fully integrate their optional component with the v3 ui

## Modification

added new page developer/developer-ui-optional-components.md

## Result

The best damn read of your life (concerning the optional component page on the v3 ui)

## Testing

open page, read.

### CODE REVIEW

**Comment by quotidian-ennui** [comment]
Sure it documents what needs to go into the POM FILE but doesn't cover what "you really need to do" if you're not using maven (!)

So, you need to have a section in there about what to put in your gradle file so that the POM is generated correctly.

**Comment by higgyfella** [comment]
> Sure it documents what needs to go into the POM FILE but doesn't cover what "you really need to do" if you're not using maven (!)
> 
> So, you need to have a section in there about what to put in your gradle file so that the POM is generated correctly.

Thanks Lewin, yeah, I'll add a new section to cover that.

**Comment by higgyfella** [comment]
Okay, I've updated the page so it now has a section about gradle, it's ready for a re-review

**Review by quotidian-ennui — APPROVED** [review]

**Review by sebastien-belin-adp — APPROVED** [review]
I made some small changes, type, styling and added syntax highlighting for groovy

**Pull request merged**
