### PR TITLE
feature/INTERLOK-3566

### PR DESCRIPTION
**Pull request by albinoloverats**
## Motivation

The documentation needs to be kept up-to-date with the software.

## Modification

Update the sections relating to JMSReplyTo and JMS ReplyTo Workflow

## Result

The documentation is up-to-date.

## Testing

Check the documentation is up-to-date.

### CODE REVIEW

**Comment by quotidian-ennui** [comment]
It's not JMSReplyTo unless we change the constant internally (JmsConstants# something) -> I think it's all just lower case, but standardising on `JMSReplyTo` makes sense for consistency.

**Comment by albinoloverats** [comment]
Ah okay. Is there any risk of changing the case of the constant? Is there likely to be anybody that is already looking to that object header and expecting it to be lowercase?

**Comment by quotidian-ennui** [comment]
@albinoloverats  it's v4; so it's either a case oif making %messageObject become case-insensistive which is OK as well; or to switch the case so that it matches getJMSReplyTo() which is the javax.jms.Message method (so JMSReplyTo in that case makes sense).

Since we are getting rid of JmsReplyToDestination, c onfiguration is broken anyway, so... it doesn't matter either way, we just have to choose :)

But what we shouldn't choose is `jmsreplyto` because that's lame :)

**Comment by albinoloverats** [comment]
I'll switch it to case-sensitive JMSReplyTo; it keeps it consistent with the other constants, especially JMS_REPLY_TO

**Review by sebastien-belin-adp — APPROVED** [review]

**Review by sebastien-belin-adp — APPROVED** [review]

**Pull request merged**
